import { SAMPLE_MAP } from "./sample_list.js";
import * as midi from "./midi.js";

// The audio context is created on first use rather than when this module is
// loaded. Browsers log an autoplay policy warning for a context created before
// any user interaction, and it keeps this module loadable without Web Audio.
//
// On iOS this is more than a warning. A context built before the page has been
// touched starts out suspended, and Safari does not always let resume() bring
// it back afterwards. Nothing here may reach for the context off the back of a
// page load: see SampleManager, which downloads the kit as the page opens but
// holds off on decoding it until there is a context to decode it with.
let audio_ctx = null;

// Whether the context exists yet, for the code that has something useful to do
// when it doesn't rather than a reason to build one
function has_audio_ctx()
{
    return audio_ctx != null;
}

function get_audio_ctx()
{
    if (!audio_ctx)
    {
        // Create AudioContext with 44.1kHz sample rate
        audio_ctx = new AudioContext({ sampleRate: 44100 });

        // Say that this is something being listened to rather than a sound
        // effect over something else. Web Audio on iOS is "ambient" audio
        // unless it says otherwise, and ambient audio is silenced by the
        // ring/silent switch on the side of the phone: a track plays with the
        // level up and the transport running and no sound comes out, with
        // nothing on the page to say why. Declaring it as playback is what
        // takes it out of that category.
        //
        // Safari 16.4 and later. The property is missing everywhere else,
        // where the switch this works around doesn't exist either.
        if (navigator.audioSession)
            navigator.audioSession.type = 'playback';
    }

    return audio_ctx;
}

//============================================================================
// Sample library
//
// This maps between the three ways of referring to a sample: its index, its
// name, and the path of its file. Note that sample_list.js is generated by
// update_samples.py and is just the raw path-to-index map.
//============================================================================

// SAMPLE_MAP maps sample paths to indices. Sample indices are stable
// over time (see update_samples.py), so a path may be missing from
// disk while its index stays reserved. We index paths by their fixed
// index rather than by position, leaving holes for any such gaps.
const sample_paths = [];
const sample_names = [];
const name_to_idx = new Map();

for (let [sample_path, sample_idx] of Object.entries(SAMPLE_MAP))
{
    let sample_name = sample_path.match(/samples\/(.+)\.wav/)[1];
    console.assert(typeof sample_name == 'string');

    sample_paths[sample_idx] = sample_path;
    sample_names[sample_idx] = sample_name;
    name_to_idx.set(sample_name, sample_idx);
}

console.assert(sample_paths.length > 0);

// Number of sample slots (highest index + 1)
export const NUM_SAMPLES = sample_paths.length;

// Sample indices in alphabetical order by name, which is how the sample
// selection UI lists them. Index order won't do: an index is assigned when a
// sample is added and never changes afterwards, so it drifts away from
// alphabetical as samples come and go. sample_list.js is generated sorted by
// name (see update_samples.py), so its own order is the one we want.
export const SORTED_SAMPLE_IDXS = Object.values(SAMPLE_MAP);

// Guard the ordering we get from sample_list.js, so that a file that somehow
// isn't sorted shows up here instead of as a scrambled sample list in the UI
console.assert(
    SORTED_SAMPLE_IDXS.every((sample_idx, i) =>
        i == 0 || sample_names[SORTED_SAMPLE_IDXS[i - 1]] < sample_names[sample_idx]
    ),
    'sample_list.js is expected to be sorted by sample name'
);

// Sample indices are encoded using 9 bits when sharing a project through a
// URL (see SAMPLE_IDX_BITS in model.js), which caps the index space at 512
console.assert(NUM_SAMPLES <= 512);

// Get the index for a given sample name
export function get_sample_idx(sample_name)
{
    console.assert(name_to_idx.has(sample_name));
    return name_to_idx.get(sample_name);
}

// Get the name of a given sample index.
// Returns undefined if no sample is associated with the index.
export function get_sample_name(sample_idx)
{
    console.assert(typeof sample_idx == 'number');
    return sample_names[sample_idx];
}

// Get the file path of a given sample index.
// Returns undefined if no sample is associated with the index. That happens
// for an index that's reserved but has no file on disk, and also for an index
// coming from a shared URL that was encoded against a longer sample list.
export function get_sample_path(sample_idx)
{
    console.assert(typeof sample_idx == 'number');
    return sample_paths[sample_idx];
}

//============================================================================
// Sample loading and playback
//============================================================================

class SampleManager
{
    constructor()
    {
        // Audio buffers for the samples, indexed by sample index
        this.sample_bufs = Array(NUM_SAMPLES);

        // Samples that have been downloaded but not yet decoded, as they came
        // off the network. Decoding is what needs an audio context, and the
        // kit starts downloading as the page opens, which is before there can
        // be one (see get_audio_ctx). These wait here until there is.
        this.raw_bufs = Array(NUM_SAMPLES);

        // Fetches currently in flight, indexed by sample index. A buffer isn't
        // stored until it finishes decoding, so we need this to know that a
        // sample is already on its way and avoid downloading it twice.
        this.pending_fetches = Array(NUM_SAMPLES);
    }

    // Turn a downloaded sample into an audio buffer.
    //
    // decodeAudioData takes the array buffer it is given over, so the download
    // is dropped here rather than kept around emptied out. That also makes
    // this safe to call twice on the same sample: the second call finds
    // nothing left to do.
    decode_sample(sample_idx)
    {
        let array_buffer = this.raw_bufs[sample_idx];

        if (!array_buffer)
            return Promise.resolve();

        this.raw_bufs[sample_idx] = null;

        return get_audio_ctx().decodeAudioData(array_buffer)
            .then(audio_buffer => this.sample_bufs[sample_idx] = audio_buffer)
            .catch(err => console.error(err));
    }

    // Decode everything downloaded while there was no context to decode it
    // with, which on a cold load is the whole of the starting kit
    decode_fetched()
    {
        let decoding = [];

        for (let sample_idx = 0; sample_idx < NUM_SAMPLES; ++sample_idx)
        {
            if (this.raw_bufs[sample_idx])
                decoding.push(this.decode_sample(sample_idx));
        }

        return Promise.all(decoding);
    }

    // Fetch/download a sample by index.
    // Returns a promise that settles once the sample is loaded, or immediately
    // if it's already loaded or there is no sample behind this index. Callers
    // that just want the sample on its way can ignore it.
    fetch_sample(sample_idx)
    {
        // Check if the sample is already loaded
        if (this.sample_bufs[sample_idx])
            return Promise.resolve();

        // Check if the sample is already being loaded. A buffer isn't stored
        // until it finishes decoding, so this is what tells us a sample is
        // already on its way and keeps us from downloading it twice.
        if (this.pending_fetches[sample_idx])
            return this.pending_fetches[sample_idx];

        // Downloaded already, and waiting on a context rather than on the
        // network. Asking for it again is what decodes it once there is one,
        // and downloading it a second time would be the bug this avoids.
        if (this.raw_bufs[sample_idx])
        {
            return has_audio_ctx()?
                this.decode_sample(sample_idx) : Promise.resolve();
        }

        let sample_path = get_sample_path(sample_idx);

        // There may be no sample behind this index: it can be reserved for a
        // sample no longer on disk, or come from a URL that was shared when
        // the sample list was longer. Such a row simply stays silent.
        if (!sample_path)
            return Promise.resolve();

        console.log(`Fetching ${sample_path}`);

        // Clearing the pending fetch once it settles means that a sample whose
        // fetch failed will be retried the next time it's requested
        return this.pending_fetches[sample_idx] = fetch(sample_path)
        .then(response => response.arrayBuffer())
        .then(array_buffer =>
        {
            this.raw_bufs[sample_idx] = array_buffer;

            // Decoded now if there is a context, and left for init_web_audio
            // to pick up if there isn't. Building one here to decode into is
            // what would put a context on the page before it has been touched.
            if (has_audio_ctx())
                return this.decode_sample(sample_idx);
        })
        .catch(err => console.error(err))
        .finally(() => this.pending_fetches[sample_idx] = null);

        //
        // TODO: on failure, retry once or twice after a small delay?
        // function retry(num_tries)
        //
    }

    // Get the audio buffer for a sample
    get_buffer(sample_idx)
    {
        console.assert(typeof sample_idx == 'number');

        // This returns undefined if the sample is not yet loaded,
        // or if there is no sample behind this index
        return this.sample_bufs[sample_idx];
    }

    // Play a sample at a given time relative to the audio context clock.
    //
    // The stereo position runs from -1 for hard left to 1 for hard right, and
    // the gain is a multiplier with 1 for the sample as it was recorded, both
    // on the scale the nodes work on rather than the tenths and decibels the
    // model holds; Pattern.row_stereo_pan and Pattern.row_gain convert between
    // the two. A sample playing dead centre at full level is routed straight to
    // the destination, so the nodes these cost are only paid for by the rows
    // that were actually set.
    //
    // Returns whether a voice was started, which is what the cap on a step is
    // counted in: a row that makes no sound costs nothing (see queue_pat_cells).
    play_sample(sample_idx, start_time, dst_node, stereo_pan = 0, gain = 1, send = 0)
    {
        const buffer = this.get_buffer(sample_idx);

        // If the sample is not yet loaded, do nothing
        if (!buffer)
            return false;

        // A row pulled all the way down is silent, so there is nothing to play
        if (gain == 0)
            return false;

        // A row feeding the delay is tapped after its level and its panning, so
        // that its echoes sit where the row sits and come down with it as it is
        // turned down. That takes a panner even on a row sitting dead centre,
        // which a dry row does without: echoes arriving somewhere other than
        // where the sound they came from is would read as a second instrument
        // rather than as that one repeating.
        if (stereo_pan != 0 || send > 0)
        {
            const panner = get_audio_ctx().createStereoPanner();
            panner.pan.value = stereo_pan;
            panner.connect(dst_node);

            if (send > 0)
            {
                const send_node = get_audio_ctx().createGain();
                send_node.gain.value = send;
                send_node.connect(get_delay_input());
                panner.connect(send_node);
            }

            dst_node = panner;
        }

        if (gain != 1)
        {
            const gain_node = get_audio_ctx().createGain();
            gain_node.gain.value = gain;
            gain_node.connect(dst_node);
            dst_node = gain_node;
        }

        // Create a buffer source
        const source = get_audio_ctx().createBufferSource();
        source.buffer = buffer;
        source.connect(dst_node);

        // Start playback at the specified time on the audio context clock
        source.start(start_time);

        return true;
    }
}

const samples = new SampleManager();

// Request that a single sample be loaded, by index.
// Loading is asynchronous, and a sample already loaded is not fetched again.
// Returns a promise that settles once the sample is available.
export function fetch_sample(sample_idx)
{
    return samples.fetch_sample(sample_idx);
}

// Request the samples used by a pattern
export function fetch_pattern_samples(pattern)
{
    for (let sample_idx of pattern.sample_idxs)
        samples.fetch_sample(sample_idx);
}

// Request the samples used by every pattern of a project
export function fetch_project_samples(project)
{
    for (let pattern of project.patterns)
        fetch_pattern_samples(pattern);
}

//============================================================================
// Audio output
//============================================================================

// Global volume/gain node
let global_gain = null;

// Master volume, in the [0, 1] range. This defaults to 45% to protect end
// users when loading somebody else's project (see design.md).
let volume = 0.45;

// Initialize the web audio context
async function init_web_audio()
{
    // If already initialized, stop
    if (global_gain)
        return;

    console.log('Initializing web audio');

    // Global volume node
    let ctx = get_audio_ctx();
    global_gain = ctx.createGain();
    global_gain.gain.setValueAtTime(volume, ctx.currentTime);
    global_gain.connect(ctx.destination);

    // A project loaded from a link can arrive with its filter already swept,
    // which there was nowhere to put it until now
    apply_filter();

    // The audio context starts out in a paused state.
    //
    // This has to be reached without waiting on anything first: iOS only lets
    // a context start from inside the gesture that asked for it, and an await
    // before this point ends the gesture as far as the browser is concerned.
    // Everything above is synchronous for that reason, and anything added here
    // belongs after this line rather than before it.
    await ctx.resume();

    // The kit was downloaded while the page was opening, when there was no
    // context to decode it into. There is one now.
    await samples.decode_fetched();
}

// Set the master volume, in the [0, 1] range
export function set_volume(new_volume)
{
    console.assert(new_volume >= 0 && new_volume <= 1);
    volume = new_volume;

    // The gain node only exists once the audio context is initialized
    if (global_gain)
        global_gain.gain.setValueAtTime(volume, get_audio_ctx().currentTime);
}

//============================================================================
// Delay
//
// One delay for the whole project, fed by whichever rows were sent to it (see
// MIN_SEND in model.js). It sits on the master gain like any other voice, so
// the master volume brings the echoes down with everything else, and it is
// left running when playback stops so that a tail rings out instead of being
// cut off mid-repeat.
//============================================================================

// Longest delay the line has to be able to hold, in seconds. A DelayNode is
// given this when it's built and can't grow afterwards, so it's the worst case
// rather than the usual one: the longest setting is 16 steps, and a step is at
// its longest at the bottom of the tempo range, which puts it at 6 seconds.
const MAX_DELAY_SECS = 8;

// Where the repeats lose their top end, in Hz.
//
// Every pass through the delay is rolled off here, so an echo arrives darker
// than what it came from and darker again on the pass after that, the way a
// tape or a bucket-brigade delay behaves. This isn't a nicety on a drum
// machine: drums are almost entirely transient, and a feedback loop with
// nothing damping it stacks those transients into a bright hash within three
// or four repeats. It isn't a control, because there is no setting of it worth
// having the tail get harsher for.
const DELAY_DAMP_FREQ = 4500;

// The delay nodes, built on first use. A project that sends nothing to the
// delay never builds them, and so pays nothing for a delay it can't hear.
let delay_input = null;
let delay_node = null;
let delay_fb = null;

// What the delay is currently set to, kept here the way the master volume is:
// the setting is held whether or not the nodes exist, so that a delay built
// later comes up already set the way the project asks for.
let delay_time = 0;
let delay_fb_gain = 0;

// Node the voices sent to the delay are connected to, building the delay if
// this is the first of them
function get_delay_input()
{
    if (delay_input)
        return delay_input;

    let ctx = get_audio_ctx();

    // What comes in is summed here and handed to the line. This is a node of
    // its own rather than the line itself so that the voices have something to
    // connect to that isn't part of the feedback loop below.
    delay_input = ctx.createGain();

    delay_node = ctx.createDelay(MAX_DELAY_SECS);
    delay_node.delayTime.value = delay_time;

    // The loop: what comes out of the line is rolled off, brought down, and put
    // back in. Web Audio allows a cycle only if there is a delay in it, which
    // is what makes this legal to build at all.
    let damp = ctx.createBiquadFilter();
    damp.type = 'lowpass';
    damp.frequency.value = DELAY_DAMP_FREQ;

    delay_fb = ctx.createGain();
    delay_fb.gain.value = delay_fb_gain;

    delay_input.connect(delay_node);
    delay_node.connect(damp);
    damp.connect(delay_fb);
    delay_fb.connect(delay_node);

    // The echoes reach the output; the dry sound of a row got there on its own
    delay_node.connect(global_gain);

    return delay_input;
}

// Apply a project's delay settings to the audio graph.
//
// Called both while playback runs, so that moving the tempo moves the echoes
// with it, and when the delay controls themselves are moved, so that a change
// is heard on a tail still ringing after playback has stopped.
export function update_delay(project)
{
    // A delay time is set rather than ramped to, so moving the control steps
    // cleanly from one setting to the next. Doing it on a line that is ringing
    // re-reads the buffer at a new rate and bends the pitch of whatever is
    // still in it, which is what a delay has always done when its time is
    // changed, and is worth having on a control somebody can grab mid-song.
    let new_time = project.delay_time_secs;
    let new_fb = project.delay_feedback_gain;

    // Both are written only when they actually change, since this runs on
    // every playback update and scheduling a value a node is already at would
    // pile up events for nothing
    if (new_time != delay_time)
    {
        delay_time = new_time;

        if (delay_node)
            delay_node.delayTime.setValueAtTime(delay_time, get_audio_ctx().currentTime);
    }

    if (new_fb != delay_fb_gain)
    {
        delay_fb_gain = new_fb;

        if (delay_fb)
            delay_fb.gain.setValueAtTime(delay_fb_gain, get_audio_ctx().currentTime);
    }
}

//============================================================================
// Filter
//
// One filter for the whole project, sitting across the master gain on the way
// out, so that it takes the echoes and everything else with it the way the
// filter on a DJ mixer does. It is set with a single control that does nothing
// at its centre (see MIN_FILTER in model.js).
//
// The master gain feeds three paths, and what the control does is fade between
// them: a dry path that is up while the control sits at its centre, and a
// low-pass and a high-pass chain, one of which comes up as the control leaves
// it. Nothing is connected or disconnected and no node's type is ever changed
// while it can be heard, which is what keeps the crossing silent. Both of
// those are steps that no amount of ramping can smooth, being a connection and
// a property rather than anything with a value over time.
//
// Fading rather than switching is also free of the usual crossfade problem.
// Near the centre the filtered path is barely filtering, so the two paths
// carry very nearly the same signal, and two copies of the same signal faded
// between sum to exactly themselves.
//============================================================================

// The filter paths, built the first time the control is moved off its centre.
// A project that never touches it never builds them, and goes on running with
// the master gain wired straight to the output.
//
// Each filtered path is two biquads rather than one, for the slope: a single
// biquad rolls off at 12 dB per octave, and a pair at 24, which is what the
// filters people know the sound of are built at. The two stages differ only in
// how hard each peaks at the corner (see FILTER_POLE_Q in model.js).
let filter_dry = null;
let filter_lp = null;
let filter_hp = null;

// The gain at the end of each of the three paths, which is what the control
// actually moves
let filter_dry_gain = null;
let filter_lp_gain = null;
let filter_hp_gain = null;

// What the filter is currently set to, held here whether or not the nodes
// exist, the way the delay settings are: a project loaded before the audio
// context is running still has its filter waiting when the graph is built.
let filter_type = null;
let filter_freq = 0;
let filter_pole_q = 0;
let filter_q = 0;

// How long the filter takes to reach a setting it has been moved to, and to
// fade between its paths, in seconds.
//
// Its settings are glided to rather than stepped to, which is the opposite of
// what the delay time does and for the opposite reason. Stepping a delay time
// re-reads a ringing line at a new rate and bends the pitch of what is in it,
// which is a sound worth having. Stepping a filter's coefficients discontinues
// its output instead, and the more resonance it has the more energy is sitting
// in its memory to be discontinued: it clicks, on the one control here that is
// meant to be swept while the track runs.
//
// Short enough that the filter still arrives where the control is by the time
// anyone could notice it hadn't, and long enough to cover the jump.
const FILTER_GLIDE_SECS = 0.015;

// Build the three paths and wire them in place of the master gain's own route
// to the output. The dry path starts up and the other two down, which is what
// the graph was already doing, so this is silent.
function build_filter()
{
    let ctx = get_audio_ctx();

    filter_dry_gain = ctx.createGain();
    filter_lp_gain = ctx.createGain();
    filter_hp_gain = ctx.createGain();

    filter_dry_gain.gain.value = 1;
    filter_lp_gain.gain.value = 0;
    filter_hp_gain.gain.value = 0;

    // Two stages per path. The first of each only supplies slope and is set
    // once: it holds the pair flat, and resonance is the other stage's to add.
    function make_chain(type, out_gain)
    {
        let stage1 = ctx.createBiquadFilter();
        let stage2 = ctx.createBiquadFilter();

        stage1.type = type;
        stage2.type = type;
        stage1.Q.value = filter_pole_q;

        stage1.connect(stage2);
        stage2.connect(out_gain);
        out_gain.connect(ctx.destination);

        return [stage1, stage2];
    }

    filter_lp = make_chain('lowpass', filter_lp_gain);
    filter_hp = make_chain('highpass', filter_hp_gain);
    filter_dry = filter_dry_gain;

    // The master gain fed the output directly until now, and feeds the three
    // paths instead from here on. The dry one is up, so what comes out is
    // unchanged.
    global_gain.disconnect();
    global_gain.connect(filter_dry_gain);
    global_gain.connect(filter_lp[0]);
    global_gain.connect(filter_hp[0]);
    filter_dry_gain.connect(ctx.destination);
}

// Apply a project's filter settings to the audio graph.
//
// Called when the controls are moved and when a project is loaded. Unlike the
// delay this doesn't follow the tempo: a filter is set in Hz, and a song
// played faster is the same song through the same filter.
export function update_filter(project)
{
    let new_type = project.filter_type;
    let new_freq = project.filter_freq;
    let new_q = project.filter_q;

    if (new_type == filter_type && new_freq == filter_freq && new_q == filter_q)
        return;

    filter_type = new_type;
    filter_freq = new_freq;
    filter_pole_q = project.filter_pole_q;
    filter_q = new_q;

    apply_filter();
}

// Set the filter nodes to whatever the filter is currently set to, building
// them if this is the first time it has been asked for, and fade to whichever
// path the setting calls for. Also called once the audio context comes up,
// since a project can be loaded from a link with its filter already swept,
// long before there is anything to hear it through.
function apply_filter()
{
    // Nothing to do before there is a graph to do it to, and nothing to build
    // for a project that has left the filter at its centre
    if (!global_gain || (!filter_dry && filter_type === null))
        return;

    let ctx = get_audio_ctx();
    let now = ctx.currentTime;

    if (!filter_dry)
        build_filter();

    // Where the corner is set only matters on the path that is coming up, but
    // both are moved: the one that is going down is where the control will
    // come back through, and a path left behind at an old setting would have
    // to jump to catch up the next time it was faded in.
    //
    // A path that is silent is set outright rather than glided, there being
    // nothing audible to glide. One that can be heard glides, which is what
    // keeps a sweep from clicking its way across the band.
    if (filter_freq !== null)
    {
        for (let [chain, out_gain] of [[filter_lp, filter_lp_gain], [filter_hp, filter_hp_gain]])
        {
            let audible = out_gain.gain.value > 0;

            for (let stage of chain)
            {
                if (audible)
                    stage.frequency.setTargetAtTime(filter_freq, now, FILTER_GLIDE_SECS);
                else
                    stage.frequency.setValueAtTime(filter_freq, now);
            }

            if (audible)
                chain[1].Q.setTargetAtTime(filter_q, now, FILTER_GLIDE_SECS);
            else
                chain[1].Q.setValueAtTime(filter_q, now);
        }
    }

    // And fade to the path this setting calls for. All three are always
    // connected, so this is the whole of what switching between them is.
    let wanted = [
        [filter_dry_gain, filter_type === null],
        [filter_lp_gain, filter_type == 'lowpass'],
        [filter_hp_gain, filter_type == 'highpass'],
    ];

    for (let [gain, up] of wanted)
        gain.gain.setTargetAtTime(up? 1:0, now, FILTER_GLIDE_SECS);
}

// Play a sample once, right away, to preview what it sounds like.
//
// The sample is loaded first if it isn't loaded yet, so previewing a sample
// being heard for the first time plays it when it arrives rather than dropping
// it. It goes through the master volume like everything else, and can overlap
// with playback, which is what makes it usable while a pattern is running.
export async function preview_sample(sample_idx)
{
    await init_web_audio();
    await samples.fetch_sample(sample_idx);

    samples.play_sample(sample_idx, get_audio_ctx().currentTime, global_gain);
}

//============================================================================
// Playback scheduling
//
// Playback is scheduled ahead of time on the audio context clock, from a timer
// running on the main thread. The timer only has to keep up on average: it
// queues every step falling inside the lookahead window, so a late callback
// makes no audible difference as long as it lands within that window.
//============================================================================

// How far ahead of the audio clock we queue samples, in seconds
const LOOKAHEAD_TIME = 0.1;

// Take the correlation between the audio clock and the performance clock, and
// return a function converting a time on the first to one on the second. That
// is the timebase MIDI sends are stamped in, the audio clock being private to
// Web Audio.
//
// getOutputTimestamp correlates the two by naming the frame leaving the output
// device (contextTime) and the moment it leaves (performanceTime), so the
// mapping carries the output latency with it: a pulse comes out stamped for
// when the audio beside it is heard rather than for when it was rendered,
// which is the difference between hardware that is roughly in time and
// hardware that is in time.
//
// The correlation is taken once and handed out as a closure rather than read
// per message. The two clocks drift slowly against each other, and re-reading
// it between the pulses of one update would move those pulses against each
// other over a window where nothing has actually drifted.
function perf_time_mapper()
{
    let ctx = get_audio_ctx();
    let ts = ctx.getOutputTimestamp? ctx.getOutputTimestamp() : null;

    // Both fields read zero until the context has rendered anything, which is
    // the answer "no correlation yet" rather than a correlation at the origin
    if (ts && ts.contextTime)
    {
        let perf_time = ts.performanceTime;
        let ctx_time = ts.contextTime;
        return audio_time => perf_time + (audio_time - ctx_time) * 1000;
    }

    // Where there is no correlation to be had, the latency the one above would
    // have carried is added by hand
    let perf_time = performance.now();
    let ctx_time = ctx.currentTime - (ctx.outputLatency || 0);
    return audio_time => perf_time + (audio_time - ctx_time) * 1000;
}

// How often the playback update runs, in milliseconds
const UPDATE_INTERV_MS = 1000 / 25;

// How many voices one step may start.
//
// Playing the song plays every pattern the timeline lays across a step, so what
// a step can start is bounded by the project rather than by the pattern being
// edited: 64 patterns of 16 rows is 1024 voices on a single step, which at the
// top of the tempo range is some 19,000 sample starts a second, and the link
// carrying that is a couple of thousand characters. Somebody opening a link
// they were sent shouldn't be able to have their tab locked up by it.
//
// This is counted per step rather than per second because that's the musical
// quantity: how many things land at once. A cap on the rate would thin out a
// fast song and leave a slow one alone at the same density, which is a limit
// nobody could make sense of by ear. The densest song in the corpus puts 10
// voices on a step and a single pattern can only ever start 16, so this sits
// several times above anything worth writing while keeping the worst case to a
// few hundred voices sounding at once, which is what a phone can carry.
export const MAX_STEP_VOICES = 64;

// What playback is currently doing. A single pattern is played while it's
// being edited, and the whole timeline is played to hear the song; both are the
// same scheduler running over a different set of steps, and only one of them
// can run at a time (see design.md).
const PLAY_PATTERN = 'pattern';
const PLAY_SONG = 'song';

// Interval to update the audio playback
let update_interv = null;

// Whether playback is playing a single pattern or the song
let play_mode = PLAY_PATTERN;

// Project currently being played, and index of the pattern being played
let play_project = null;
let play_pat_idx = 0;

// Pattern waiting to take over from the one playing, null if there is none.
// Selecting another pattern mid-playback doesn't cut the current one off: the
// new pattern is launched at the end of the current pattern's cycle.
let queued_pat_idx = null;

// Global step at which the playing pattern's current cycle started. A pattern
// is launched from its first step, so where a pattern is in its cycle is
// measured from here rather than from the global step counter itself, which
// keeps running across pattern changes.
let play_pat_start = 0;

// Step of the song currently being queued, and the global step the current
// pass through the song started at. The song loops, so these play the same
// role for song playback that the two above play for a pattern.
let song_step = 0;
let song_start = 0;

// Audio context time at the last playback update
let last_time = 0;

// Playback position we last queued until
// Monotonically increasing position in fractional steps
let last_pos = 0;

// Index of the next step to be queued. Steps have a fixed duration, so this is
// a single global step counter shared by every pattern: a pattern just plays
// step `next_step % pat.num_steps`. That's what makes patterns of different
// lengths phase against each other, and it means we don't need to keep a
// playback position per pattern.
let next_step = 0;

// Test if playback is currently running
export function is_playing()
{
    return update_interv != null;
}

// Test if playback is currently playing a single pattern
export function is_playing_pattern()
{
    return is_playing() && play_mode == PLAY_PATTERN;
}

// Test if playback is currently playing the song
export function is_playing_song()
{
    return is_playing() && play_mode == PLAY_SONG;
}

// Index of the pattern currently being heard, or null if no single pattern is
// being played. Song playback has several patterns sounding at once, so there
// is no one pattern being heard to report.
export function get_play_pat_idx()
{
    return is_playing_pattern()? play_pat_idx : null;
}

// Index of the pattern waiting to take over at the end of the current
// pattern's cycle, or null if there is none
export function get_queued_pat_idx()
{
    return is_playing_pattern()? queued_pat_idx : null;
}

// Global step currently being heard.
//
// The scheduler runs ahead of the audio clock, so the position it has queued
// up to is not the position to show. We get the audible one by evaluating the
// same straight line the scheduler uses, at the current time rather than at
// the queue horizon, which is behind it.
function get_audible_step()
{
    let delta_time = get_audio_ctx().currentTime - last_time;
    return Math.floor(last_pos + delta_time * play_project.steps_per_sec);
}

// Get the step of the playing pattern currently being heard, or null if no
// single pattern is being played
export function get_play_step()
{
    if (!is_playing_pattern())
        return null;

    // Two things put the audible position behind the start of the pattern's
    // cycle: the first update queues ahead of the start of playback, and a
    // queued pattern is swapped in at the queue horizon, so at a pattern change
    // the new pattern becomes current up to one lookahead window before it can
    // be heard. Both resolve within that window, and clamping holds the
    // position at the first step until they do.
    let pat = play_project.patterns[play_pat_idx];
    return Math.max(0, get_audible_step() - play_pat_start) % pat.num_steps;
}

// Get the step of the song currently being heard, or null if the song isn't
// being played
export function get_song_step()
{
    if (!is_playing_song())
        return null;

    // The song loops at the queue horizon, so just after a loop the audible
    // position is still behind the start of the pass being queued. Clamping
    // holds it at the first step for the one lookahead window that takes.
    let song_len = play_project.song_num_steps;
    return song_len > 0?
        Math.max(0, get_audible_step() - song_start) % song_len :
        null;
}

// Get the step a given pattern is currently being heard at in the song, or
// null if that pattern isn't sounding: the song isn't playing, or the timeline
// doesn't place this pattern across the position being heard.
//
// A pattern plays the step of its own that the song step falls on, which is
// what makes patterns of different lengths phase against each other. That rule
// belongs to queue_song_step, and is applied here rather than by the caller so
// that the highlight can't come to disagree with what's audible.
export function get_song_pat_step(pat_idx)
{
    let song_step = get_song_step();

    if (song_step === null)
        return null;

    // A pattern only sounds where the timeline places it. Everywhere else its
    // grid is silent, and a step running across it would say otherwise.
    if (!play_project.pat_active_at(pat_idx, song_step))
        return null;

    return song_step % play_project.patterns[pat_idx].num_steps;
}

// Queue a pattern to be launched at the end of the pattern currently playing,
// so that selecting a pattern doesn't cut off the one being heard. Queuing the
// pattern already playing cancels a pending queue instead.
// Does nothing when playback isn't running.
export function queue_pattern(pat_idx)
{
    // Selecting a pattern during song playback only opens it for editing: what
    // plays then is what the timeline says, not what's on screen
    if (!is_playing_pattern())
        return;

    console.assert(pat_idx < play_project.patterns.length);

    queued_pat_idx = (pat_idx == play_pat_idx)? null : pat_idx;
}

// Move song playback to a given step of the song.
//
// Steps are queued ahead of the audio clock, so this takes hold at the queue
// horizon: what was already queued at the old position is still heard, for at
// most the one lookahead window it covers.
//
// Does nothing when the song isn't playing, or when the step asked for is past
// the end of the song. Playing a single pattern has no position to move to that
// the pattern doesn't already come back to on its own.
export function seek_song(step_idx)
{
    if (!is_playing_song())
        return;

    console.assert(step_idx >= 0);

    // The song can have gotten shorter since the click, and the timeline shows
    // room past the end of the song to place patterns in, which is not somewhere
    // the song can be played from
    if (step_idx >= play_project.song_num_steps)
        return;

    // Swing holds back every other step of the global counter, so where the song
    // sits on that counter is what decides which half of the beat gets held
    // back. The song starts on an even offset and a seek keeps it there, by
    // landing on the step next to the one asked for when it has to: a sixteenth
    // of accuracy costs less than a groove that comes back inverted.
    if ((next_step - step_idx) % 2)
        step_idx += (step_idx > 0)? -1 : 1;

    // The step counter keeps running across the seek, so where the song is now
    // being played from is written as an offset against it, the same way the
    // start of a pass through the song is
    song_step = step_idx;
    song_start = next_step - step_idx;
}

// Keep playback consistent with a pattern having been deleted from the
// project. Patterns are referred to by index, so deleting one renumbers those
// after it (see Project.delete_pattern).
export function pattern_deleted(pat_idx)
{
    // Song playback reads the patterns and lanes of the project as it goes, so
    // it has nothing of its own to fix up
    if (!is_playing_pattern())
        return;

    // The pattern being heard is gone, so there is nothing to keep playing
    if (pat_idx == play_pat_idx)
    {
        stop_playback();
        return;
    }

    if (play_pat_idx > pat_idx)
        play_pat_idx--;

    if (queued_pat_idx === pat_idx)
        queued_pat_idx = null;
    else if (queued_pat_idx !== null && queued_pat_idx > pat_idx)
        queued_pat_idx--;
}

// Start playing a single pattern of a project
export async function play_pattern(project, pat_idx)
{
    console.assert(pat_idx < project.patterns.length);

    play_pat_idx = pat_idx;
    queued_pat_idx = null;
    play_pat_start = 0;

    await start_playback(project, PLAY_PATTERN);
}

// Start playing the song, i.e. the patterns placed on the timeline.
// Does nothing if no pattern is placed on the timeline, since there is then
// no song to play.
export async function play_song(project)
{
    if (project.song_num_steps == 0)
        return;

    song_step = 0;
    song_start = 0;

    await start_playback(project, PLAY_SONG);
}

// Start playback in a given mode. Playing a pattern and playing the song are
// the same scheduler running over a different set of steps, and starting
// either one ends whatever was playing before it.
async function start_playback(project, mode)
{
    stop_playback();

    await init_web_audio();

    play_project = project;
    play_mode = mode;

    // Reset the playback position. The audio clock has been running ever since
    // the audio context was created, so we anchor the position to the current
    // time, otherwise the first update would try to queue every step elapsed
    // since page load.
    last_time = get_audio_ctx().currentTime;
    last_pos = 0;
    next_step = 0;

    // The MIDI clock runs off the same position, so it is reset here with it.
    // This only arms the clock: the Start message goes out from the first
    // update, alongside the first pulse it can be timed against.
    midi.start_clock();

    // Queue the first steps immediately, so that playback starts without
    // waiting for the first interval to elapse. This is also what starts the
    // interval: an empty song stops playback instead of starting it.
    update_interv = setInterval(update_playback, UPDATE_INTERV_MS);
    update_playback();
}

// Stop playback
export function stop_playback()
{
    if (!is_playing())
        return;

    clearInterval(update_interv);
    update_interv = null;
    play_project = null;

    midi.stop_clock();
}

// Update playback
function update_playback()
{
    // Read the step rate from the project on every update, so that changing
    // the tempo during playback takes effect immediately
    let steps_per_sec = play_project.steps_per_sec;

    // How long a swung step is held back for, in seconds. Read here for the
    // same reason the step rate is: moving the swing slider during playback
    // takes effect on the steps queued from here on.
    let swing_time = play_project.swing_delay / steps_per_sec;

    // And the delay for the same reason again. It's set in steps, so it has to
    // follow the tempo as well as its own controls.
    update_delay(play_project);

    // Time to queue until
    let queue_until_t = get_audio_ctx().currentTime + LOOKAHEAD_TIME;

    // Advance the position by however much time elapsed since the last update.
    // We accumulate a delta instead of computing the position directly from the
    // audio clock so that moving the tempo slider mid-playback only affects the
    // steps queued from here on, instead of retroactively rescaling the position
    // of everything already played, which would make the playback jump.
    let delta_time = queue_until_t - last_time;
    let delta_steps = delta_time * steps_per_sec;
    let queue_until_pos = last_pos + delta_steps;

    // Read the song length on every update too, since the song ends wherever
    // the last pattern placed on the timeline does. Emptying the timeline
    // during playback leaves no song to keep playing.
    let song_len = 0;

    if (play_mode == PLAY_SONG)
    {
        song_len = play_project.song_num_steps;

        if (song_len == 0)
        {
            stop_playback();
            return;
        }
    }

    // Lay the MIDI clock over the same window, off the same straight line the
    // steps below are back-projected from, so that the pulses and the samples
    // can't come apart however the tempo is moved while they run. Note that
    // the positions handed over are the unswung ones: see queue_clock.
    let to_perf_time = perf_time_mapper();

    midi.queue_clock(
        queue_until_pos,
        pos => to_perf_time(queue_until_t - (queue_until_pos - pos) / steps_per_sec)
    );

    // For each step falling inside the lookahead window
    for (; next_step <= queue_until_pos; ++next_step)
    {
        // Back-project the time of this step from the queue horizon
        let step_time = queue_until_t - (queue_until_pos - next_step) / steps_per_sec;

        // Swing holds back every other step of the grid, which is what turns an
        // even run of steps into a groove. It moves when a step is heard without
        // moving the step counter, so the position everything else works in
        // stays the straight line back-projected above, and the steps still come
        // out in order: a step is never held back as far as the next one.
        //
        // Which steps swing is decided on the global step counter rather than
        // on a position within a pattern, so that patterns of different lengths
        // swing with each other rather than against each other.
        if (next_step % 2)
            step_time += swing_time;

        if (play_mode == PLAY_SONG)
            queue_song_step(step_time, song_len);
        else
            queue_pat_step(step_time);
    }

    last_time = queue_until_t;
    last_pos = queue_until_pos;
}

// Queue one step of the pattern being played
function queue_pat_step(step_time)
{
    let pat = play_project.patterns[play_pat_idx];
    let step_idx = (next_step - play_pat_start) % pat.num_steps;

    // A queued pattern is launched once the playing one reaches the end of its
    // cycle. This is tested per step rather than once per update, because the
    // lookahead window can straddle the end of a cycle.
    if (queued_pat_idx !== null && step_idx == 0)
    {
        play_pat_idx = queued_pat_idx;
        queued_pat_idx = null;
        play_pat_start = next_step;

        // The new pattern is launched from its first step, whatever its
        // length, rather than picking up the phase of the previous one
        pat = play_project.patterns[play_pat_idx];
        step_idx = 0;
    }

    // A pattern has at most MAX_PAT_ROWS rows, so playing one on its own can
    // never reach the cap. It's passed anyway so that there is one path here.
    queue_pat_cells(pat, step_idx, step_time, MAX_STEP_VOICES);
}

// Queue one step of the song, i.e. of every pattern placed on the timeline at
// that step. Steps have a fixed duration, so a pattern plays the step of its
// own that the song step falls on, which is what makes patterns of different
// lengths phase against each other.
function queue_song_step(step_time, song_len)
{
    // Loop back to the start of the song at the end. The song can have gotten
    // shorter since the last step, hence testing rather than comparing.
    if (song_step >= song_len)
    {
        song_step = 0;
        song_start = next_step;
    }

    // Voices are counted across the whole step, since it's everything landing
    // at once that the cap is about, not any one pattern's share of it. The
    // patterns are gone through in the order they're held in, so a step over
    // the cap is one the last patterns of the project drop out of.
    let num_voices = 0;

    for (let pat_idx = 0; pat_idx < play_project.num_patterns; ++pat_idx)
    {
        if (!play_project.pat_active_at(pat_idx, song_step))
            continue;

        let pat = play_project.patterns[pat_idx];

        num_voices += queue_pat_cells(
            pat,
            song_step % pat.num_steps,
            step_time,
            MAX_STEP_VOICES - num_voices
        );

        if (num_voices >= MAX_STEP_VOICES)
            break;
    }

    song_step++;
}

//============================================================================
// Humanizing
//
// Timing and level are scattered per hit, so that a row playing the same step
// through a whole song doesn't play it identically each time.
//
// Both spreads are one-sided: a hit is pushed late and pulled down, never
// early and never up. That costs less than it looks like it does, because what
// is heard is the spread between hits -- two rows on one step coming apart, a
// run of hats sitting unevenly -- and that is the same either way. The only
// thing a constant lateness has to be late against is the MIDI clock, which
// stays straight (see queue_clock), and at these spans that is a few
// milliseconds of external gear running ahead. Pulling down rather than up is
// what keeps a hit from ever exceeding the level its row was set to, which
// matters most on the steps where every row lands at once.
//
// The amounts themselves belong to the project, which is what says what its
// controls mean (see humanize_time). What lives here is how they are drawn.
//============================================================================

// Where the tail of a spread is cut off, in standard deviations. A normal
// distribution has no bound of its own, and one hit in a few hundred landing
// three times further out than the rest reads as a mistake rather than as
// looseness.
const HUMANIZE_MAX_DEVS = 2.5;

// How much of the timing spread a sample gets, by the prefix its name starts
// with. Anything not named here gets all of it.
//
// The kick is what the ear takes the pulse from: scattering it doesn't loosen
// the groove, it moves the groove, and a beat whose pulse wanders sounds wrong
// rather than played. The backbeat anchors nearly as hard and gives up a
// little less.
//
// Level is deliberately not scaled this way. A drummer's kicks vary in weight
// like everything else does, and it is only in time that the rest of the kit
// is heard against them.
const HUMANIZE_TIME_SCALES = [
    ['kick_', 0.25],
    ['snare_', 0.6],
    ['clap_', 0.6],
];

// The above resolved per sample index, so that a hit is a lookup rather than a
// walk down a list of prefixes. Indices are reserved permanently and may have
// no sample behind them (see sample_paths), and a hole gets the full spread it
// would have gotten as an unrecognized name.
const humanize_time_scales = [];
for (let sample_idx = 0; sample_idx < NUM_SAMPLES; ++sample_idx)
{
    let sample_name = sample_names[sample_idx];

    let scale = sample_name?
        HUMANIZE_TIME_SCALES.find(([prefix]) => sample_name.startsWith(prefix)) :
        null;

    humanize_time_scales[sample_idx] = scale? scale[1] : 1;
}

// Draw from the positive half of a normal distribution with the given standard
// deviation, cut off at HUMANIZE_MAX_DEVS.
//
// Normal rather than uniform because that is the shape the deviations of a
// played part actually take: most hits land near where they were aimed and a
// few stray, where a uniform draw makes every distance from the grid equally
// likely and comes out sounding shaken rather than loose.
function draw_spread(sigma)
{
    // Box-Muller. The log needs something that can't be zero, which is what
    // subtracting from one gives: random() returns a value in [0, 1).
    let u = 1 - Math.random();
    let v = Math.random();
    let devs = Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);

    return Math.min(Math.abs(devs), HUMANIZE_MAX_DEVS) * sigma;
}

// Trigger the sample of each active cell on one step of a pattern, stopping
// once it has started as many voices as it is allowed to.
// There is one row per sample, and the number of rows is variable.
//
// Returns how many voices were started, which is what the caller counts the
// cap in. A row whose sample hasn't loaded or that was pulled all the way down
// starts nothing, and so is not charged for: the cap is there to bound the work
// and the noise a step makes, and a row making neither costs nothing on either.
function queue_pat_cells(pat, step_idx, step_time, max_voices)
{
    let num_voices = 0;

    // How far the hits of this step may be scattered. Read once per step
    // rather than per hit, so that everything landing together is queued at
    // one setting even if the control is moved while the step is being built.
    let time_spread = play_project.humanize_time;
    let gain_spread = play_project.humanize_gain;
    let max_offs = play_project.humanize_max_offs;

    for (let row_idx = 0; row_idx < pat.num_rows; ++row_idx)
    {
        if (num_voices >= max_voices)
            break;

        if (!pat.get_cell(row_idx, step_idx))
            continue;

        let sample_idx = pat.sample_idxs[row_idx];
        let hit_time = step_time;
        let gain = pat.row_gain(row_idx);

        // Every hit is drawn for on its own, which is the whole point of it:
        // two rows sharing a step come apart because they drew different
        // offsets, and a row repeating a step is loosened by drawing again.
        if (time_spread > 0)
        {
            let sample_spread = time_spread * humanize_time_scales[sample_idx];
            hit_time += Math.min(draw_spread(sample_spread), max_offs);
        }

        // Scaled rather than offset, so that a row pulled all the way down
        // stays silent instead of being nudged back into audibility
        if (gain_spread > 0)
            gain *= 10 ** (-draw_spread(gain_spread) / 20);

        let started = samples.play_sample(
            sample_idx,
            hit_time,
            global_gain,
            pat.row_stereo_pan(row_idx),
            gain,
            pat.row_send_gain(row_idx)
        );

        if (started)
            ++num_voices;
    }

    return num_voices;
}
