import { SAMPLE_MAP } from "./sample_list.js";

// The audio context is created on first use rather than when this module is
// loaded. Browsers log an autoplay policy warning for a context created before
// any user interaction, and it keeps this module loadable without Web Audio.
let audio_ctx = null;

function get_audio_ctx()
{
    // Create AudioContext with 44.1kHz sample rate
    if (!audio_ctx)
        audio_ctx = new AudioContext({ sampleRate: 44100 });

    return audio_ctx;
}

//============================================================================
// Sample library
//
// This maps between the three ways of referring to a sample: its index, its
// name, and the path of its file. Note that sample_list.js is generated by
// update_samples.py and is just the raw path-to-index map.
//============================================================================

// SAMPLE_MAP maps sample paths to indices. Sample indices are stable
// over time (see update_samples.py), so a path may be missing from
// disk while its index stays reserved. We index paths by their fixed
// index rather than by position, leaving holes for any such gaps.
const sample_paths = [];
const sample_names = [];
const name_to_idx = new Map();

for (let [sample_path, sample_idx] of Object.entries(SAMPLE_MAP))
{
    let sample_name = sample_path.match(/samples\/(.+)\.wav/)[1];
    console.assert(typeof sample_name == 'string');

    sample_paths[sample_idx] = sample_path;
    sample_names[sample_idx] = sample_name;
    name_to_idx.set(sample_name, sample_idx);
}

console.assert(sample_paths.length > 0);

// Number of sample slots (highest index + 1)
export const NUM_SAMPLES = sample_paths.length;

// Sample indices in alphabetical order by name, which is how the sample
// selection UI lists them. Index order won't do: an index is assigned when a
// sample is added and never changes afterwards, so it drifts away from
// alphabetical as samples come and go. sample_list.js is generated sorted by
// name (see update_samples.py), so its own order is the one we want.
export const SORTED_SAMPLE_IDXS = Object.values(SAMPLE_MAP);

// Guard the ordering we get from sample_list.js, so that a file that somehow
// isn't sorted shows up here instead of as a scrambled sample list in the UI
console.assert(
    SORTED_SAMPLE_IDXS.every((sample_idx, i) =>
        i == 0 || sample_names[SORTED_SAMPLE_IDXS[i - 1]] < sample_names[sample_idx]
    ),
    'sample_list.js is expected to be sorted by sample name'
);

// Sample indices are encoded using 9 bits when sharing a project through a
// URL (see SAMPLE_IDX_BITS in model.js), which caps the index space at 512
console.assert(NUM_SAMPLES <= 512);

// Get the index for a given sample name
export function get_sample_idx(sample_name)
{
    console.assert(name_to_idx.has(sample_name));
    return name_to_idx.get(sample_name);
}

// Get the name of a given sample index.
// Returns undefined if no sample is associated with the index.
export function get_sample_name(sample_idx)
{
    console.assert(typeof sample_idx == 'number');
    return sample_names[sample_idx];
}

// Get the file path of a given sample index.
// Returns undefined if no sample is associated with the index. That happens
// for an index that's reserved but has no file on disk, and also for an index
// coming from a shared URL that was encoded against a longer sample list.
export function get_sample_path(sample_idx)
{
    console.assert(typeof sample_idx == 'number');
    return sample_paths[sample_idx];
}

//============================================================================
// Sample loading and playback
//============================================================================

class SampleManager
{
    constructor()
    {
        // Audio buffers for the samples, indexed by sample index
        this.sample_bufs = Array(NUM_SAMPLES);

        // Fetches currently in flight, indexed by sample index. A buffer isn't
        // stored until it finishes decoding, so we need this to know that a
        // sample is already on its way and avoid downloading it twice.
        this.pending_fetches = Array(NUM_SAMPLES);
    }

    // Fetch/download a sample by index.
    // Returns a promise that settles once the sample is loaded, or immediately
    // if it's already loaded or there is no sample behind this index. Callers
    // that just want the sample on its way can ignore it.
    fetch_sample(sample_idx)
    {
        // Check if the sample is already loaded
        if (this.sample_bufs[sample_idx])
            return Promise.resolve();

        // Check if the sample is already being loaded. A buffer isn't stored
        // until it finishes decoding, so this is what tells us a sample is
        // already on its way and keeps us from downloading it twice.
        if (this.pending_fetches[sample_idx])
            return this.pending_fetches[sample_idx];

        let sample_path = get_sample_path(sample_idx);

        // There may be no sample behind this index: it can be reserved for a
        // sample no longer on disk, or come from a URL that was shared when
        // the sample list was longer. Such a row simply stays silent.
        if (!sample_path)
            return Promise.resolve();

        console.log(`Fetching ${sample_path}`);

        // Clearing the pending fetch once it settles means that a sample whose
        // fetch failed will be retried the next time it's requested
        return this.pending_fetches[sample_idx] = fetch(sample_path)
        .then(response => response.arrayBuffer())
        .then(array_buffer => get_audio_ctx().decodeAudioData(array_buffer))
        .then(audio_buffer => this.sample_bufs[sample_idx] = audio_buffer)
        .catch(err => console.error(err))
        .finally(() => this.pending_fetches[sample_idx] = null);

        //
        // TODO: on failure, retry once or twice after a small delay?
        // function retry(num_tries)
        //
    }

    // Get the audio buffer for a sample
    get_buffer(sample_idx)
    {
        console.assert(typeof sample_idx == 'number');

        // This returns undefined if the sample is not yet loaded,
        // or if there is no sample behind this index
        return this.sample_bufs[sample_idx];
    }

    // Play a sample at a given time relative to the audio context clock
    play_sample(sample_idx, start_time, dst_node)
    {
        const buffer = this.get_buffer(sample_idx);

        // If the sample is not yet loaded, do nothing
        if (!buffer)
            return;

        // Create a buffer source
        const source = get_audio_ctx().createBufferSource();
        source.buffer = buffer;
        source.connect(dst_node);

        // Start playback at the specified time on the audio context clock
        source.start(start_time);
    }
}

const samples = new SampleManager();

// Request that a single sample be loaded, by index.
// Loading is asynchronous, and a sample already loaded is not fetched again.
// Returns a promise that settles once the sample is available.
export function fetch_sample(sample_idx)
{
    return samples.fetch_sample(sample_idx);
}

// Request the samples used by a pattern
export function fetch_pattern_samples(pattern)
{
    for (let sample_idx of pattern.sample_idxs)
        samples.fetch_sample(sample_idx);
}

// Request the samples used by every pattern of a project
export function fetch_project_samples(project)
{
    for (let pattern of project.patterns)
        fetch_pattern_samples(pattern);
}

//============================================================================
// Audio output
//============================================================================

// Global volume/gain node
let global_gain = null;

// Master volume, in the [0, 1] range. This defaults to 50% to protect end
// users when loading somebody else's project (see design.md).
let volume = 0.5;

// Initialize the web audio context
async function init_web_audio()
{
    // If already initialized, stop
    if (global_gain)
        return;

    console.log('Initializing web audio');

    // Global volume node
    let ctx = get_audio_ctx();
    global_gain = ctx.createGain();
    global_gain.gain.setValueAtTime(volume, ctx.currentTime);
    global_gain.connect(ctx.destination);

    // The audio context starts out in a paused state
    await ctx.resume();
}

// Set the master volume, in the [0, 1] range
export function set_volume(new_volume)
{
    console.assert(new_volume >= 0 && new_volume <= 1);
    volume = new_volume;

    // The gain node only exists once the audio context is initialized
    if (global_gain)
        global_gain.gain.setValueAtTime(volume, get_audio_ctx().currentTime);
}

// Play a sample once, right away, to preview what it sounds like.
//
// The sample is loaded first if it isn't loaded yet, so previewing a sample
// being heard for the first time plays it when it arrives rather than dropping
// it. It goes through the master volume like everything else, and can overlap
// with playback, which is what makes it usable while a pattern is running.
export async function preview_sample(sample_idx)
{
    await init_web_audio();
    await samples.fetch_sample(sample_idx);

    samples.play_sample(sample_idx, get_audio_ctx().currentTime, global_gain);
}

//============================================================================
// Playback scheduling
//
// Playback is scheduled ahead of time on the audio context clock, from a timer
// running on the main thread. The timer only has to keep up on average: it
// queues every step falling inside the lookahead window, so a late callback
// makes no audible difference as long as it lands within that window.
//============================================================================

// How far ahead of the audio clock we queue samples, in seconds
const LOOKAHEAD_TIME = 0.1;

// How often the playback update runs, in milliseconds
const UPDATE_INTERV_MS = 1000 / 25;

// What playback is currently doing. A single pattern is played while it's
// being edited, and the whole timeline is played to hear the song; both are the
// same scheduler running over a different set of steps, and only one of them
// can run at a time (see design.md).
const PLAY_PATTERN = 'pattern';
const PLAY_SONG = 'song';

// Interval to update the audio playback
let update_interv = null;

// Whether playback is playing a single pattern or the song
let play_mode = PLAY_PATTERN;

// Project currently being played, and index of the pattern being played
let play_project = null;
let play_pat_idx = 0;

// Pattern waiting to take over from the one playing, null if there is none.
// Selecting another pattern mid-playback doesn't cut the current one off: the
// new pattern is launched at the end of the current pattern's cycle.
let queued_pat_idx = null;

// Global step at which the playing pattern's current cycle started. A pattern
// is launched from its first step, so where a pattern is in its cycle is
// measured from here rather than from the global step counter itself, which
// keeps running across pattern changes.
let play_pat_start = 0;

// Step of the song currently being queued, and the global step the current
// pass through the song started at. The song loops, so these play the same
// role for song playback that the two above play for a pattern.
let song_step = 0;
let song_start = 0;

// Audio context time at the last playback update
let last_time = 0;

// Playback position we last queued until
// Monotonically increasing position in fractional steps
let last_pos = 0;

// Index of the next step to be queued. Steps have a fixed duration, so this is
// a single global step counter shared by every pattern: a pattern just plays
// step `next_step % pat.num_steps`. That's what makes patterns of different
// lengths phase against each other, and it means we don't need to keep a
// playback position per pattern.
let next_step = 0;

// Test if playback is currently running
export function is_playing()
{
    return update_interv != null;
}

// Test if playback is currently playing a single pattern
export function is_playing_pattern()
{
    return is_playing() && play_mode == PLAY_PATTERN;
}

// Test if playback is currently playing the song
export function is_playing_song()
{
    return is_playing() && play_mode == PLAY_SONG;
}

// Index of the pattern currently being heard, or null if no single pattern is
// being played. Song playback has several patterns sounding at once, so there
// is no one pattern being heard to report.
export function get_play_pat_idx()
{
    return is_playing_pattern()? play_pat_idx : null;
}

// Index of the pattern waiting to take over at the end of the current
// pattern's cycle, or null if there is none
export function get_queued_pat_idx()
{
    return is_playing_pattern()? queued_pat_idx : null;
}

// Global step currently being heard.
//
// The scheduler runs ahead of the audio clock, so the position it has queued
// up to is not the position to show. We get the audible one by evaluating the
// same straight line the scheduler uses, at the current time rather than at
// the queue horizon, which is behind it.
function get_audible_step()
{
    let delta_time = get_audio_ctx().currentTime - last_time;
    return Math.floor(last_pos + delta_time * play_project.steps_per_sec);
}

// Get the step of the playing pattern currently being heard, or null if no
// single pattern is being played
export function get_play_step()
{
    if (!is_playing_pattern())
        return null;

    // Two things put the audible position behind the start of the pattern's
    // cycle: the first update queues ahead of the start of playback, and a
    // queued pattern is swapped in at the queue horizon, so at a pattern change
    // the new pattern becomes current up to one lookahead window before it can
    // be heard. Both resolve within that window, and clamping holds the
    // position at the first step until they do.
    let pat = play_project.patterns[play_pat_idx];
    return Math.max(0, get_audible_step() - play_pat_start) % pat.num_steps;
}

// Get the step of the song currently being heard, or null if the song isn't
// being played
export function get_song_step()
{
    if (!is_playing_song())
        return null;

    // The song loops at the queue horizon, so just after a loop the audible
    // position is still behind the start of the pass being queued. Clamping
    // holds it at the first step for the one lookahead window that takes.
    let song_len = play_project.song_num_steps;
    return song_len > 0?
        Math.max(0, get_audible_step() - song_start) % song_len :
        null;
}

// Queue a pattern to be launched at the end of the pattern currently playing,
// so that selecting a pattern doesn't cut off the one being heard. Queuing the
// pattern already playing cancels a pending queue instead.
// Does nothing when playback isn't running.
export function queue_pattern(pat_idx)
{
    // Selecting a pattern during song playback only opens it for editing: what
    // plays then is what the timeline says, not what's on screen
    if (!is_playing_pattern())
        return;

    console.assert(pat_idx < play_project.patterns.length);

    queued_pat_idx = (pat_idx == play_pat_idx)? null : pat_idx;
}

// Keep playback consistent with a pattern having been deleted from the
// project. Patterns are referred to by index, so deleting one renumbers those
// after it (see Project.delete_pattern).
export function pattern_deleted(pat_idx)
{
    // Song playback reads the patterns and lanes of the project as it goes, so
    // it has nothing of its own to fix up
    if (!is_playing_pattern())
        return;

    // The pattern being heard is gone, so there is nothing to keep playing
    if (pat_idx == play_pat_idx)
    {
        stop_playback();
        return;
    }

    if (play_pat_idx > pat_idx)
        play_pat_idx--;

    if (queued_pat_idx === pat_idx)
        queued_pat_idx = null;
    else if (queued_pat_idx !== null && queued_pat_idx > pat_idx)
        queued_pat_idx--;
}

// Start playing a single pattern of a project
export async function play_pattern(project, pat_idx)
{
    console.assert(pat_idx < project.patterns.length);

    play_pat_idx = pat_idx;
    queued_pat_idx = null;
    play_pat_start = 0;

    await start_playback(project, PLAY_PATTERN);
}

// Start playing the song, i.e. the patterns placed on the timeline.
// Does nothing if no pattern is placed on the timeline, since there is then
// no song to play.
export async function play_song(project)
{
    if (project.song_num_steps == 0)
        return;

    song_step = 0;
    song_start = 0;

    await start_playback(project, PLAY_SONG);
}

// Start playback in a given mode. Playing a pattern and playing the song are
// the same scheduler running over a different set of steps, and starting
// either one ends whatever was playing before it.
async function start_playback(project, mode)
{
    stop_playback();

    await init_web_audio();

    play_project = project;
    play_mode = mode;

    // Reset the playback position. The audio clock has been running ever since
    // the audio context was created, so we anchor the position to the current
    // time, otherwise the first update would try to queue every step elapsed
    // since page load.
    last_time = get_audio_ctx().currentTime;
    last_pos = 0;
    next_step = 0;

    // Queue the first steps immediately, so that playback starts without
    // waiting for the first interval to elapse. This is also what starts the
    // interval: an empty song stops playback instead of starting it.
    update_interv = setInterval(update_playback, UPDATE_INTERV_MS);
    update_playback();
}

// Stop playback
export function stop_playback()
{
    if (!is_playing())
        return;

    clearInterval(update_interv);
    update_interv = null;
    play_project = null;
}

// Update playback
function update_playback()
{
    // Read the step rate from the project on every update, so that changing
    // the tempo during playback takes effect immediately
    let steps_per_sec = play_project.steps_per_sec;

    // Time to queue until
    let queue_until_t = get_audio_ctx().currentTime + LOOKAHEAD_TIME;

    // Advance the position by however much time elapsed since the last update.
    // We accumulate a delta instead of computing the position directly from the
    // audio clock so that moving the tempo slider mid-playback only affects the
    // steps queued from here on, instead of retroactively rescaling the position
    // of everything already played, which would make the playback jump.
    let delta_time = queue_until_t - last_time;
    let delta_steps = delta_time * steps_per_sec;
    let queue_until_pos = last_pos + delta_steps;

    // Read the song length on every update too, since the song ends wherever
    // the last pattern placed on the timeline does. Emptying the timeline
    // during playback leaves no song to keep playing.
    let song_len = 0;

    if (play_mode == PLAY_SONG)
    {
        song_len = play_project.song_num_steps;

        if (song_len == 0)
        {
            stop_playback();
            return;
        }
    }

    // For each step falling inside the lookahead window
    for (; next_step <= queue_until_pos; ++next_step)
    {
        // Back-project the time of this step from the queue horizon
        let step_time = queue_until_t - (queue_until_pos - next_step) / steps_per_sec;

        if (play_mode == PLAY_SONG)
            queue_song_step(step_time, song_len);
        else
            queue_pat_step(step_time);
    }

    last_time = queue_until_t;
    last_pos = queue_until_pos;
}

// Queue one step of the pattern being played
function queue_pat_step(step_time)
{
    let pat = play_project.patterns[play_pat_idx];
    let step_idx = (next_step - play_pat_start) % pat.num_steps;

    // A queued pattern is launched once the playing one reaches the end of its
    // cycle. This is tested per step rather than once per update, because the
    // lookahead window can straddle the end of a cycle.
    if (queued_pat_idx !== null && step_idx == 0)
    {
        play_pat_idx = queued_pat_idx;
        queued_pat_idx = null;
        play_pat_start = next_step;

        // The new pattern is launched from its first step, whatever its
        // length, rather than picking up the phase of the previous one
        pat = play_project.patterns[play_pat_idx];
        step_idx = 0;
    }

    queue_pat_cells(pat, step_idx, step_time);
}

// Queue one step of the song, i.e. of every pattern placed on the timeline at
// that step. Steps have a fixed duration, so a pattern plays the step of its
// own that the song step falls on, which is what makes patterns of different
// lengths phase against each other.
function queue_song_step(step_time, song_len)
{
    // Loop back to the start of the song at the end. The song can have gotten
    // shorter since the last step, hence testing rather than comparing.
    if (song_step >= song_len)
    {
        song_step = 0;
        song_start = next_step;
    }

    for (let pat_idx = 0; pat_idx < play_project.num_patterns; ++pat_idx)
    {
        if (!play_project.pat_active_at(pat_idx, song_step))
            continue;

        let pat = play_project.patterns[pat_idx];
        queue_pat_cells(pat, song_step % pat.num_steps, step_time);
    }

    song_step++;
}

// Trigger the sample of each active cell on one step of a pattern.
// There is one row per sample, and the number of rows is variable.
function queue_pat_cells(pat, step_idx, step_time)
{
    for (let row_idx = 0; row_idx < pat.num_rows; ++row_idx)
    {
        if (pat.get_cell(row_idx, step_idx))
            samples.play_sample(pat.sample_idxs[row_idx], step_time, global_gain);
    }
}
