// The link every song in tests/corpus.js encodes to, pinned.
//
// A link is the only thing a Groovie project is ever saved as, so a link that
// has been shared has to keep opening as the song it was made from for as long
// as the app is up. These strings are what holds the encoding to that. The
// corpus is the widest set of songs there is, covering every field the format
// carries and both ends of the ranges they hold, so pinning what all of it
// encodes to pins the format itself rather than a corner of it.
//
// tests/encoding.test.js checks both directions: that each song still encodes
// to the string here, and that the string still decodes to that song. The
// first catches the encoder writing something new, the second catches the
// decoder reading an old link as a different song, which is the one that
// matters once links are out in the world.
//
// A failure here is not something to re-freeze. Until the encoding is
// versioned it means the change under test breaks every link already shared,
// and the change is what has to give. Once ENCODING_VERSION moves, the links
// below stay as they are and go on being decoded by whatever reads version 0,
// with a table of their own added for the version that replaced it.
//
// Generated by tools/update_golden.js, which is only for when the corpus
// itself changes. Each link is left on one line however long it gets, since a
// link is one string and a broken-up one can't be pasted into a browser.

export const GOLDEN_LINKS = {
    "the amen break":
        "untitled/BgBA_MEUQOLAXGGsElCXs4a1qAwaDUHg",

    "a drum and bass roller":
        "untitled/CGBA_UEUQOGFYCACdworVFVTqa7b-LPECCQoBEIEkhxrqBB24h1oAghrDTnpAA",

    "a 32 bar hip hop arrangement":
        "untitled/AyBEfMN60AQFuMBBHhcWk3S99MSlSh85wBB8CMFfKrX_-DFAr_llh86MPRd4XkQekfOmCGPSZTxjxL6kXiIoXE2sSSR98okA",

    "a 32 bar techno arrangement":
        "untitled/BaBEfEPRjhSJekfPuBJBHCkS4YkBfS1LHz74EaK_xff_fyR9O8gjxLxLigckkfkrBgI6SPqncA",

    "a 64 bar house arrangement":
        "untitled/BUBHPEOBjheJe-2LsfEJ6CdcXEzW5-Lli5HxAiBGCeJqatc-Jexcj4iKckk8BVDMtr8laJefkB8CfwBxO-AEGIijjlAD9Vf5pIfIEUQcCCCOF4l8UkfIYYERU_-E_q7_x38Hoq-qSfkBtQgV2nBCsABBk5GI_fUrAA",

    "patterns of prime lengths":
        "untitled/BQBEPENigOFQl77BAFuS_ZRcgwAbJH3TeCgATokfVLsMAcygvylUAA",

    "a default kit barely touched":
        "untitled/BQBCPKUB5BHhelSQ89KCH79wIII-kqB5SgP4IC_6qv_8AA",

    "a 32 bar house groove panned wide":
        "untitled/BUNDfUOBjgQQR4kZyAh8BDkCAHAQwIJT60SsfbvgRgn6RHH79-4ihH_Fj6AQQRwnEjMLyAh8BK0gQFgeYEEp-JUHmORQAWO5EBWNpBCWBCPFfqSA",

    "a 64 bar psytrance arrangement":
        "untitled/BpBFPUORjiAJ24YiRC0KQTUoto4IpEYRPQ3h79-_fv37kcQQCjI4gJM7iXol7KXIe_f48_79-_cekr0ZWA1GBFLinsp4-hIlAVIHVCAmCSgNAjECSUT0naFQgiiApjilh5DX0RV2IUgm4FJZxS3GrCxBDoQgzoHcSQid9TvA",

    "a dub techno arrangement":
        "untitled/BUAngZ5BwMcKBIZWBBBBjG-w8BZTKvPWY4uw8RKRwRJsDUWQQSxL2LkPGjHE5IlRPMxTwA",

    "a 32 bar two step arrangement":
        "untitled/BgYm4b5h6oBULcZCCCGzwqEkFCBbUXbfg0V72LHz1oAgLfAjBWphFFX4BBAJdrErLyEb5JJRJVAoDALWBAhI8kmkByZVVoprGnn4kSkBYcs0RqbW3gCLmkqSAA",

    "a 64 bar drill and bass arrangement":
        "untitled/B9ATI_5htYoCCAImhWOL9cICQhhNTEuGBTQszLjv36cmILUJCQERFJMkCIK1qWpZ-eQCgiBBCRRAjjXAiCRSCAVFZjaWhcFV2e_nsVIbBIiCQkxIJRQiixxLEl4iJICCKCBFyOSZT1ASSGk0JiFx1q0misRcCIgTmdSiU0mRsgG8UlIoZ5wGwIiBCCCgi0YBjCOtVLx8hn4rr77_NYTG6rBEgQESKApNnvpKr_LPLPE4j6kA8Ag2ASR0iZrn2IlYuQflAFNAC5AiCT0VQxEhEz9UsA",

    "the longest song there can be":
        "untitled/BhBHPGMeQR7_9ES_7Rj7oOEJwh2IiiSKfrLiV47_DAC9FjlfKfV0FABCRQgx_qc6hARZpxGhFoHooMQ99sdIMA5IgpL3MZuy3MZuyJAPiKgkespf1IsARpAemf_do3w",

    "a hardcore stomp at the top of the range":
        "untitled/Dwy_4J5CGMbwWiSjbY1kEAMN1h5CIF-gSQRDe4sA",

    "a doom crawl at the bottom of the range":
        "untitled/AAAAAB5SgOCKIWI5I4GolWA",

    "a sixteen row percussion wall":
        "untitled/A8BBf-MeQR4XkBemSnP7TpWdL9FXot9F_0SPOSKPSBD0QedrW-kjHwiBFAes_EWvyRQ6y5JFE5qGox6w",

    "a phasing pulse of tiny patterns":
        "untitled/BcBMAAK5mb_sBANZXt_yBABsgq3zpkDAWZJ6vEv4FAD5CEnxKcCAAT0RFTiV0EgIvSQOjxKKDQHJIHNV_VIiAnJASIl-4UAI0gKSP_YKgPiQGgofrPwI5oAU1Z2OnLr9A5XY_ASmABTVn7dPBjWNgA",
};
