#!/usr/bin/env node

// Regenerates tests/golden_links.js, the pinned link for every song in the
// corpus.
//
// The pinned links are what says that a link shared today still opens as the
// song it was made from. That means this script is not something to reach for
// when the tests fail: a failure there is the encoding having changed what it
// writes, and the links people hold changing with it. Run it only when the
// corpus itself has changed, i.e. a song was added, removed or rewritten, or
// when the encoding version has been stepped and the old links have been given
// a decoder of their own to be tested against.
//
// Run it with `node tools/update_golden.js` from anywhere in the repo. It
// overwrites the file, so check what it did with `git diff` before keeping it:
// the only lines that should move are the ones for songs you meant to touch.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { CORPUS, build_song } from "../tests/corpus.js";
import { project_to_hash } from "../model.js";

const OUT_PATH = fileURLToPath(new URL('../tests/golden_links.js', import.meta.url));

const HEADER = `// The link every song in tests/corpus.js encodes to, pinned.
//
// A link is the only thing a Groovie project is ever saved as, so a link that
// has been shared has to keep opening as the song it was made from for as long
// as the app is up. These strings are what holds the encoding to that. The
// corpus is the widest set of songs there is, covering every field the format
// carries and both ends of the ranges they hold, so pinning what all of it
// encodes to pins the format itself rather than a corner of it.
//
// tests/encoding.test.js checks both directions: that each song still encodes
// to the string here, and that the string still decodes to that song. The
// first catches the encoder writing something new, the second catches the
// decoder reading an old link as a different song, which is the one that
// matters once links are out in the world.
//
// A failure here is not something to re-freeze. Until the encoding is
// versioned it means the change under test breaks every link already shared,
// and the change is what has to give. Once ENCODING_VERSION moves, the links
// below stay as they are and go on being decoded by whatever reads version 0,
// with a table of their own added for the version that replaced it.
//
// Generated by tools/update_golden.js, which is only for when the corpus
// itself changes. Each link is left on one line however long it gets, since a
// link is one string and a broken-up one can't be pasted into a browser.

export const GOLDEN_LINKS = {
`;

const FOOTER = `};
`;

let body = CORPUS.map(song =>
{
    let hash = project_to_hash(build_song(song));
    return `    ${JSON.stringify(song.name)}:\n        ${JSON.stringify(hash)},\n`;
}).join('\n');

writeFileSync(OUT_PATH, HEADER + body + FOOTER);

console.log(`wrote ${CORPUS.length} links to tests/golden_links.js`);
